In [20]:
import pandas as pd
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [29]:
df = pd.read_csv('/home/ishita/Machine_learning/Dataset/breast-cancer-wisconsin.data')

In [30]:
df.head()

id  clump_thickness  unif_cell_size  unif_cell_shape  marg_adhension  \
0  1000025                5               1                1               1   
1  1002945                5               4                4               5   
2  1015425                3               1                1               1   
3  1016277                6               8                8               1   
4  1017023                4               1                1               3   

   single_epith_cell_size bare_nuclei  bland_chrom  normal_nucleoli  mitoses  \
0                       2           1            3                1        1   
1                       7          10            3                2        1   
2                       2           2            3                1        1   
3                       3           4            3                7        1   
4                       2           1            3                1        1   

   class  
0      2  
1      2  
2      2  
3      2  
4      2

In [31]:
df.replace('?', -99999, inplace=True) # outlier

In [32]:
df.drop(columns='id',axis = 1 , inplace=True)

In [33]:
X = np.array(df.drop(['class'],axis=1))

<IPython.core.display.Javascript object>

In [34]:
y = np.array(df['class'])

<IPython.core.display.Javascript object>

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [36]:
clf = svm.SVC()

In [37]:
clf.fit(X_train, y_train)

SVC()

In [38]:
accuracy = clf.score(X_test, y_test)
accuracy

0.5928571428571429

In [39]:
example_measures = np.array([[4,2,1,1,1,2,3,2,1],[4,2,1,2,2,2,3,2,1]])
example_measures

<IPython.core.display.Javascript object>

array([[4, 2, 1, 1, 1, 2, 3, 2, 1],
       [4, 2, 1, 2, 2, 2, 3, 2, 1]])

In [40]:
example_measures = example_measures.reshape(len(example_measures),-1)

In [41]:
example_measures

array([[4, 2, 1, 1, 1, 2, 3, 2, 1],
       [4, 2, 1, 2, 2, 2, 3, 2, 1]])

In [42]:
prediction = clf.predict(example_measures)
prediction

array([2, 2])